project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!homeworks"
    - "!activities"
    - "!labs"
    - "!lectures"
  
name: "dku-stats-101-sp2024"

website:
  title: "DKU Stats 101 - Spring 2024"
  navbar: 
    left:
      - text: "Course Introduction"
        href: index.html
      - text: "Schedule and Course Materials"
        href: schedulematerials.html
      - text: "Homework"
        href: homework.html
      - text: "R Help Manual"
        href: rmanual.html
    right: 
      - icon: github
        href: https://github.com/andrewmacd/dkustats101spring2024

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true



