---
title: "Course Schedule and Class Materials"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Important: class schedule is subject to change, contingent on mitigating circumstances and the progress we make as a class. If there are any changes, I will announce them on the Teams site.

# Unit 1: Distributions

## Lecture 1.1: Class welcome (Wednesday, March 22)

Reading to do before class: Chapter 1, 2.1 and 2.2, and 3

Topics covered:

-   What are data and variables?
-   How to display quantitative and qualitative variables
-   Contingency tables

## Lecture 1.2: Characteristics of distributions (Thursday, March 23)

Reading to do before class: Chapter 2.3-5 and 4

> Preclass quiz due at 2:30 pm

Topics covered:

-   How to describe the shape, center, and spread of a distribution

-   How to compare distributions

-   Dealing with problem distributions (outliers, reexpression)

-   Lecture webpage: [Lecture 1.2](https://andrewm.shinyapps.io/spr2023distributions/)

-   Lecture activity: [Lecture 1.2 activity](activities/Lecture 1.2/lecture1.2.activity.zip)

-   Quality YouTube content: [Tidyverse music video](https://www.youtube.com/watch?v=p8Py9C8iq2s&ab_channel=TheRaf)

## Online lab 1.1 (due Sunday, March 26 at 11:59:00 pm)

-   [Introduction to R](https://learn.datacamp.com/courses/free-introduction-to-r)
-   [Introduction to the Tidyverse](https://learn.datacamp.com/courses/introduction-to-the-tidyverse)

## Lab 1.1: R and Quarto familiarization (Monday, March 27)

-   Lab files: [Lab 1.1](labs/Lab 1.1/lab1.1.zip)
    -   Make sure to extract (unzip) the lab files before attempting to modify them!

## Lecture 1.3: Comparing distributions and the Normal distribution (Tuesday, March 28)

Reading to do before class: Chapter 5

> Preclass quiz due at 2:30 pm

Topics covered:

-   Standard deviation and standardizing values

-   Normal models

-   Normal percentiles

-   Lecture webpage: [Lecture 1.3](https://andrewm.shinyapps.io/spr2023advanceddistributions/)

-   Lecture activity: [Lecture 1.3 activity](activities/Lecture 1.3/lecture1.3.activity.zip)

## Lab 1.2: Advanced Quarto editing (Wednesday, March 29)

-   Lab files: [Lab 1.2](labs/Lab 1.2/lab1.2.zip)
    -   Make sure to extract (unzip) the lab files before attempting to modify them!

## Unit 1 homework (due April 2nd at 23:59:00 pm)

-   Homework files: [Unit 1 homework instructions](homeworks/Unit 1 Homework/homework1.zip)

# Unit 2: Relationships between variables

## Lecture 2.1: Association and correlation (Thursday, March 30)

Reading to do before class: Chapter 6

> Preclass quiz due at 2:30 pm

Topics covered:

-   Scatterplots

-   Correlations

-   Does correlation imply causation?

-   Lecture webpage: [Lecture 2.1](https://andrewm.shinyapps.io/spr2023association)

-   Lecture activity: [Lecture 2.1 activity](activities/Lecture 2.1/lecture2.1.activity.zip)

## Online lab 2.1 (due on Friday, March 31 at 23:59:00)

-   [Introduction to Data Visualization with ggplot2](https://learn.datacamp.com/courses/introduction-to-data-visualization-with-ggplot2)

## Lecture 2.2: Simple Linear Regression (Tuesday, April 4)

Reading to do before class: Chapter 7

> Preclass quiz due at 2:30 pm

Topics covered:

-   Line of best fit: least squares

-   The linear model

-   What are residuals

-   Regression assumptions

-   Lecture webpage: [Lecture 2.2](https://andrewm.shinyapps.io/spr2023simpleregression)

-   Lecture activity: [Lecture 2.2 activity](activities/Lecture 2.2/lecture2.2.activity.zip)

## Lab 2.1: Working with regressions (Thursday, April 6)

-   Lab files: [Lab 2.1](labs/Lab 2.1/lab2.1.zip)
    -   Make sure to extract (unzip) the lab files before attempting to modify them!

## Lecture 2.3: Regression Wisdom (Friday, April 7)

Reading to do before class: Chapter 8

> Preclass quiz due at 2:30 pm China time China time

Topics covered:

-   Beware extrapolation

-   Outliers and leverage

-   Lurking variables

-   Straightening scatterplots

-   Lecture webpage: [Lecture 2.3](https://andrewm.shinyapps.io/spr2023regressionwisdom)

-   Lecture activity: [Lecture 2.3 activity](activities/Lecture 2.3/lecture2.3.activity.zip)

## Online lab 2.2 (due on Friday, April 7 at 23:59:00)

-   [Working with Dates and Times in R](https://www.datacamp.com/courses/working-with-dates-and-times-in-r)

## Unit 2 homework - midterm project - progress check (due Monday, April 10 at 23:59:00)

-   Homework files: [Unit 2 homework instructions](homeworks/Unit 2 Homework - Midterm/midterm.zip)

## Lecture 2.4: Multiple Regression (Tuesday, April 11)

Reading to do before class: Chapter 9

> Preclass quiz due at 2:30 pm

Topics covered:

-   What is multiple regression?

-   Interpreting multiple regression coefficients

-   Partial regression plots

-   Indicator variables

-   Lecture webpage: [Lecture 2.4](https://andrewm.shinyapps.io/spr2023multipleregression)

-   Lecture activity: [Lecture 2.4 activity](activities/Lecture 2.4/lecture2.4.activity.zip)

## Lab 2.2: Interpreting Coefficients (Wednesday, April 12)

-   Lab files: [Lab 2.2](labs/Lab 2.2/lab2.2.zip)
    -   Make sure to extract (unzip) the lab files before attempting to modify them!

## Online lab 2.3 (due on Friday, April 14 at 11:59:00)

-   [Intermediate Data Visualization with ggplot2](https://app.datacamp.com/learn/courses/intermediate-data-visualization-with-ggplot2)

## Unit 2 homework - midterm project (due Sunday, April 16 at 11:59:00)

-   Homework files: [Unit 2 homework instructions](homeworks/Unit 2 Homework - Midterm/midterm.zip)

# Unit 3: Measuring uncertainty

## Lecture 3.1: Confidence intervals - poroportions (Thursday, April 13)

Reading to do before class: Chapter 13

> Preclass quiz due at 2:30 pm China time

Topics covered:

-   What is a sampling distribution?

-   When does the normal model apply?

-   Constructing a confidence interval

-   Interpreting a confidence interval

-   Lecture webpage: [Lecture 3.1](https://andrewm.shinyapps.io/spr2023confintprop)

-   Lecture activity: [Lecture 3.1 activity](activities/Lecture 3.1/lecture3.1.activity.zip)

## Lecture 3.2: Confidence intervals - means (Tuesday, April 18)

Reading to do before class: Chapter 14

> Preclass quiz due at 2:30 pm China time

Topics covered:

-   The Central Limit Theorem

-   Confidence interval for means

-   Interpreting a confidence interval

-   Final thoughts on confidence intervals

-   Lecture webpage: [Lecture 3.2](https://andrewm.shinyapps.io/spr2023confintmean/)

-   Lecture activity: [Lecture 3.2 activity](activities/Lecture 3.2/lecture3.2.activity.zip)

## Lab 3.1: Bootstrapping (Wednesday, April 19)

-   Lab files: [Lab 3.1](labs/Lab 3.1/lab3.1.zip)
    -   Make sure to extract (unzip) the lab files before attempting to modify them!

## Lecture 3.3: Hypothesis testing (Thursday, April 20)

Reading to do before class: Chapter 15

> Preclass quiz due at 2:30 pm

Topics covered:

-   What are hypotheses?

-   $p$ values

-   $p$ values and decisions -- how to make a decision

-   Lecture webpage: [Lecture 3.3](https://andrewm.shinyapps.io/spr2023hyptesting/)

-   Lecture activity: [Lecture 3.3 activity](activities/Lecture 3.3/lecture3.3.activity.zip)

## Lecture 3.4: Hypothesis testing wisdom (Tuesday, April 25)

Reading to do before class: Chapter 16

> Preclass quiz due at 2:30 pm China time

Topics covered:

- Interpreting p-values

- Alpha and critical values

- Practical vs. statistical significance

- Type I and II errors

- Power of a test

-   Lecture webpage: [Lecture 3.4](https://andrewm.shinyapps.io/spr2023hyptestwisdom/)

-   Lecture activity: [Lecture 3.4 activity](activities/Lecture 3.4/lecture3.4.activity.zip)

## Lab 3.2: Sampling (Wednesday, April 26)

-   Lab files: [Lab 3.2](labs/Lab 3.2/lab3.2.zip)

## Unit 3 homework - progress check (due Wednesday, April 26 at 23:59:00)

-   Homework files: [Unit 3 homework instructions](homeworks/Unit 3 Homework/unit.3.homework.zip)

# Unit 4: Statistical inference

## Lecture 4.1: Comparing groups (Thursday, April 27)

Reading to do before class: Chapter 17

> Preclass quiz due at 2:30 pm China time

Topics covered:

-   Confidence intervals for comparing two samples

-   Assumptions and conditions for two-sample hypothesis tests

-   Two-sample $z$ test

-   Two-sample $t$ test

-   Lecture webpage: [Lecture 4.1](https://andrewm.shinyapps.io/spr2023comparinggroups/)

-   Lecture activity: [Lecture 4.1 activity](activities/Lecture 4.1/lecture4.1.activity.zip)

## Unit 3 homework (due Sunday, May 7 at 23:59:00)

-   Homework files: [Unit 3 homework instructions](homeworks/Unit 3 Homework/unit.3.homework.zip)

## Lecture 4.2: Returning to regression (Tuesday, May 9)

Reading to do before class: Chapter 20

> Preclass quiz due at 2:30 pm China time

Topics covered:

-   Regression inference and intuition

-   The regression table

-   Confidence and prediction intervals

-   Lecture webpage: [Lecture 4.2](https://andrewm.shinyapps.io/spr2023return2regression/)

-   Lecture activity: [Lecture 4.2 activity](activities/Lecture 4.2/lecture4.2.activity.zip)

## Lecture 4.3: Interpretation activity (Thursday, May 11)

-   How to read academic statistical results

-   Locating the model

-   Interpreting the test

-   Determining possible weaknesses of the model

-   Lecture paper discussion: [Paper](http://faculty.ucmerced.edu/lhamilton2/docs/Hamilton_2013_ASR.pdf)

-   Lecture activity: [Lecture 4.3 activity](activities/Lecture 4.3/lecture4.3.activity.zip)

## Unit 4 homework - paper analysis (due Sunday, May 14 at 23:59:00)

-   Homework files: [Unit 4 homework - paper analysis instructions](homeworks/Unit 4 Homework - Paper Analysis/unit.4.homework.zip)

## Final project (due Thursday, May 18 at 23:59:00)

-   Homework files:  [Final project instructions](homeworks/Final Project/final.project.zip)
